support both Ubuntu and Wolfi for package dep checking

diff --git a/wolfi-rc b/wolfi-rc
--- a/wolfi-rc
+++ b/wolfi-rc
@@ -46,12 +46,25 @@ function wolfi() {
 }
 
 function _wolfi-check-deps() {
-	type gh 2>&1 >/dev/null || error "You need to install 'git':\n sudo apt install gh"
-	type git 2>&1 >/dev/null || error "You need to install 'git':\n sudo apt install git"
-	type docker 2>&1 >/dev/null || error "You need to install 'git':\n sudo apt install docker"
-	type melange 2>&1 >/dev/null || error "You need to install 'melange':\n go install chainguard.dev/melange@latest"
-	type terraform 2>&1 >/dev/null || error "You need to install 'terraform':\n go install github.com/hashicorp/terraform@latest"
-	type yam 2>&1 >/dev/null || error "You need to install 'yam':\n go install chainguard.dev/yam@latest"
+	. /etc/os-release
+	if [ "$NAME" = "Wolfi" ]; then
+		local pkg="apk add"
+		type gh 2>&1 >/dev/null || error "Missing 'gh': sudo $pkg gh"
+		type git 2>&1 >/dev/null || error "Missing 'git': sudo $pkg git"
+		type docker 2>&1 >/dev/null || error "Missing 'docker': sudo $pkg docker"
+		type melange 2>&1 >/dev/null || error "Missing 'melange': sudo $pkg melange"
+		type terraform 2>&1 >/dev/null || error "Missing 'terraform': sudo $pkg terraform"
+		type yam 2>&1 >/dev/null || error "Missing 'yam': go install chainguard.dev/yam@latest"
+	elif [ "$NAME" = "Ubuntu" ]; then
+		local pkg="apt install"
+		type gh 2>&1 >/dev/null || error "Missing 'gh': sudo $pkg gh"
+		type git 2>&1 >/dev/null || error "Missing 'git': sudo $pkg git"
+		type docker 2>&1 >/dev/null || error "Missing 'docker': sudo $pkg docker"
+		type melange 2>&1 >/dev/null || error "Missing 'melange': go install chainguard.dev/melange@latest"
+		type terraform 2>&1 >/dev/null || error "Missing 'terraform': go install github.com/hashicorp/terraform@latest"
+		type yam 2>&1 >/dev/null || error "Missing 'yam': go install chainguard.dev/yam@latest"
+
+	fi
 	export TERRAFORM=$(command -v terraform)
 }
 
