use the new yam package on wolfi!

diff --git a/wolfi-rc b/wolfi-rc
--- a/wolfi-rc
+++ b/wolfi-rc
@@ -58,7 +58,7 @@ function _wolfi-check-deps() {
 		type make 2>&1 >/dev/null || error "Missing 'make': sudo $pkg make"
 		type melange 2>&1 >/dev/null || error "Missing 'melange': sudo $pkg melange"
 		type terraform 2>&1 >/dev/null || error "Missing 'terraform': sudo $pkg terraform"
-		type yam 2>&1 >/dev/null || error "Missing 'yam': go install github.com/chainguard-dev/yam@latest"
+		type yam 2>&1 >/dev/null || error "Missing 'yam': sudo $pkg yam"
 	elif [ "$NAME" = "Ubuntu" ] || [ "$NAME" = "Debian GNU/Linux" ]; then
 		local pkg="apt install"
 		type go 2>&1 >/dev/null || sudo snap install go --classic
